{
    "source file": "test_sag.py",
    "line number": "831",
    "func name": "test_sag_classifier_raises_error",
    "func arg": "(solver)",
    "comments": ""
}