{
    "source file": "debug_errors.py",
    "line number": "32",
    "func name": "main",
    "func arg": "(_)",
    "comments": ""
}