{
    "source file": "operator_fp_exceptions_test.py",
    "line number": "13",
    "func name": "setThrowIfFpExceptions",
    "func arg": "(enabled)",
    "comments": ""
}