{
    "source file": "test_data1.py",
    "line number": "60",
    "func name": "test_dict_instantiation_graph_obj_error_2",
    "func arg": "()",
    "comments": ""
}